### PR TITLE
Blob sysdir

### PR DESCRIPTION
**Pull request by johnraff**
`/usr/share/bunsen/utilities/blob/` is added as a config path, along with `$HOME/.config/blob`
Any themes in the user directory will be displayed first, and if there is a theme in both directories with the same name, the config details for restoring will be taken from the user version, although both will be displayed. User themes can be deleted, but not system themes.

Enabling restoration from a system theme with the same name as a user theme would require storing the full path, not just the name. This is possible, but would add complication to the code - I have tried to keep changes to a minimum. If this version is used, then the BLOB themes can be removed from /usr/share/bunsen/skel, so the user directory will be empty for new installs and only the system presets will be displayed. Users who create new themes can be expected to choose new names, so the name clash issue might not be serious..

### CODE REVIEW

**Comment by johnraff** [comment]
One simple workaround for the issue of having themes with the same name (as in the system dir) remaining in upgrading users' ~/.config/blob is to change the names of all the themes before shipping them in the new system directory. Users who then deliberately created new themes with the same names as those can be reasonably considered to be wanting to override them, no?

**Comment by tknomanzr** [comment]
^ That would be the behavior that I would expect.

**Comment by johnraff** [comment]
I think the revised bl-obthemes script now handles its new duties OK.

- System preset themes are marked with a different icon from user saved themes.
- If a theme with the exact same name exists in both places, the system theme is hidden.
- System presets cannot be deleted (of course).
- If a known icon theme is needed, an offer will be made to install the necessary package. (This applies only to **bunsen-faenza-icon-theme** at the moment, but others could easily be added.)
- Even if stored themes exist, the script starts with the 'intro' dialogue, instead of jumping straight to 'restore'.

**Comment by johnraff** [comment]
BTW the package installation functionality requires **bunsen-common** to be upgraded to the latest version, 9.0.3-1 released yesterday fixing a bug with bl-installer.

**Comment by johnraff** [comment]
Now merged into helium-dev.

**Pull request merged**
