### PR TITLE
bin/bl-obthemes: added support for zsh & KornShell

### PR DESCRIPTION
**Pull request by Head-on-a-Stick**
KornShell scans $ENV for the configuration file.

### CODE REVIEW

**Comment by johnraff** [comment]
In my bash shell $ENV is not set. Does KornShell set it, and if so, to what?

**Comment by Head-on-a-Stick** [comment]
>Does KornShell set it, and if so, to what?

The user sets $ENV and points it to the desired configuration file location, this also applies for both the Debian and Busybox Almquist Shell variants.

**Comment by johnraff** [comment]
OK we have @capn-damo 's approval to modify the code.

Just one thing, since $ENV should contain a filepath, 
`SHELLFILE=$(echo "$ENV" | awk -F'/' '{print $NF}')` 
could perhaps be replaced by 
`SHELLFILE="${ENV##*/}"`? 
Let's keep our code as clean and simple as possible!

Also, you have actually tested the modified **blobthemes**, that it sucessfully restores the file defined in $ENV? After a quick look, I couldn't see where the original path to $SHELLFILE was being preserved. Unlike .bashrc etc etc it doesn't have to be in ~/ but could be anywhere.

**Comment by Head-on-a-Stick** [comment]
> Let's keep our code as clean and simple as possible!
I am really sorry John but my scripting skills are poor to the point of being non-existent :(

I have no idea what this magic line does:
`${ENV##*/}``
But it looks *much* nicer than my version :)

Thanks!

>  have actually tested the modified blobthemes, that it sucessfully restores the file defined in $ENV?
Yes, I use BLOB on my system and I have tested it quite a bit now.
>I couldn't see where the original path to $SHELLFILE was being preserved. Unlike .bashrc etc etc it doesn't have to be in ~/ but could be anywhere.
That is an exceptionally good point, I didn't consider that at all — my addition will only work if $ENV isn't in a sub-directory of $HOME :/

Ah well, back to the drawing board — I will have a think about this.

**Comment by johnraff** [comment]
> I have no idea what this magic line does:
> ${ENV##*/}

It's part of [Bash parameter substitution](http://wiki.bash-hackers.org/syntax/pe#substring_removal) and very useful for simple string manipulation without having to invoke pipes to other programs. In this case it's saying "remove everything up to and including the rightmost forward slash".

One more general point - how far should we go in expanding blobthemes? If I got it right, it was originally conceived for backing up *graphic presentation* rather than configs in general. (Why not just back up the whole of ~/.config/, for example?) What kind of configuration usually goes in the file referenced in $ENV?

**Comment by Head-on-a-Stick** [comment]
> What kind of configuration usually goes in the file referenced in $ENV?

Just the (interactive) shell configuration settings, that is the intended (POSIX) use for that variable.

**Comment by capn-damo** [comment]
> One more general point - how far should we go in expanding blobthemes? If I got it right, it was originally conceived for backing up *graphic presentation* rather than configs in general. (Why not just back up the whole of ~/.config/, for example?)

The original idea was to save a unified collection of themed visual elements ie conky, tint2, wallpaper, gtk/ob themes etc. Terminal colours were later added because they can also be part of the graphical theme. I had got fed up of manually changing a conky after setting a wallpaper!

It was also meant to follow the BL default installation, so having different shells, QT themes, window managers etc adds a whole lot more complexity. Run with how you like, but then it could be in danger of losing the KISS approach ;) However, a bash+yad script will never add much bloat no matter how comprehensive it gets.

**Comment by Head-on-a-Stick** [comment]
I'm going to close this because I don't think it adds anything useful and my coding is too awful for words :)

Thanks for your input folks.

**Pull request closed without merging**
